# Generated by Django 3.2.4 on 2021-06-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brew_shareapi', '0002_auto_20210614_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brewmethod',
            old_name='user',
            new_name='brewer',
        ),
        migrations.RenameField(
            model_name='coffee',
            old_name='user',
            new_name='brewer',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='user',
            new_name='brewer',
        ),
        migrations.RenameField(
            model_name='favoriteentry',
            old_name='user',
            new_name='brewer',
        ),
        migrations.RenameField(
            model_name='recipereview',
            old_name='user',
            new_name='brewer',
        ),
    ]
