# Generated by Django 3.2.4 on 2021-07-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew_shareapi', '0002_auto_20210624_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewer',
            name='cloudinary_image_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='brewmethod',
            name='cloudinary_image_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='coffee',
            name='cloudinary_image_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entrystep',
            name='cloudinary_image_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='brewer',
            name='profile_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='coffee_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='entrystep',
            name='step_image',
            field=models.URLField(blank=True),
        ),
    ]
