# Generated by Django 3.2.4 on 2021-06-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brew_shareapi', '0003_auto_20210614_1555'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntryFlag',
            new_name='EntryReport',
        ),
    ]
