# Generated by Django 3.2.4 on 2021-06-15 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brew_shareapi', '0004_rename_entryflag_entryreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewer',
            name='current_brew_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='brewer',
            name='current_coffee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='brewer',
            name='private',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='brewmethod',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='review',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tasting_notes',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entryreport',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin', to='brew_shareapi.brewer'),
        ),
        migrations.AlterField(
            model_name='entryreport',
            name='resolution',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recommendrecipe',
            name='confirmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='confirmer', to='brew_shareapi.brewer'),
        ),
    ]
