# Generated by Django 3.2.4 on 2021-06-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew_shareapi', '0005_auto_20210615_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='website',
            field=models.CharField(max_length=255),
        ),
    ]
