# Generated by Django 3.2.4 on 2021-06-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew_shareapi', '0006_alter_coffee_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='coffee_image',
            field=models.ImageField(blank=True, null=True, upload_to='coffee_pics/%Y/%m/%d'),
        ),
    ]
