# Generated by Django 3.2.4 on 2021-06-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew_shareapi', '0007_alter_coffee_coffee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewmethod',
            name='method_image',
            field=models.ImageField(blank=True, null=True, upload_to='method_pics/%Y/%m/%d'),
        ),
    ]
