# Generated by Django 3.2.4 on 2021-06-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew_shareapi', '0008_alter_brewmethod_method_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewmethod',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
