# Generated by Django 3.2.4 on 2021-06-22 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brew_shareapi', '0010_auto_20210619_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewer',
            name='favorites',
            field=models.ManyToManyField(related_name='liked', through='brew_shareapi.FavoriteEntry', to='brew_shareapi.Entry'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='brewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='brew_shareapi.brewer'),
        ),
        migrations.AlterField(
            model_name='entrystep',
            name='step_image',
            field=models.ImageField(blank=True, null=True, upload_to='step_pics/%Y/%m/%d'),
        ),
    ]
